# Generated by Django 4.0.6 on 2022-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_charge',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
